#!groovy

WORK_NODE = ''


stage("Select a target node lable") {

    node('master') {

        echo "Start prepare..."

        if (BRANCH_NAME == 'devops_develop') {
            WORK_NODE = 'chstage-node'
        } else if (BRANCH_NAME == 'devops_prod') {
            WORK_NODE = 'chstage-node'
        }
        echo "end prepare the Node is ${WORK_NODE}..."
        sh 'printenv'
    }
}


node(WORK_NODE){

  stage("0 of 3 Set environment"){
    //Local paths
    WORK_DIR = pwd() //"${BASE_DIR}/${WS_DIR}"
    SCRIPTS_DIR = "${WORK_DIR}/Devops"

    //MySQL config
    MYSQL_CONFIG = "/home/jenkins/ch-stage/scripts/mysql.json"
    SERVER_CONFIG_DIR = "${WORK_DIR}/Config/secrets/"

    //Build config
    VAPOR = "/usr/local/bin/vapor"
    BUILD_PARAM = "--verbose --release"

    //Deploy config
    env.CH_BUILD = "${env.WORKSPACE}"  // export to scripts
    env.CH_WEBROOT = "/var/www/stage" // export to scripts
    DEPLOY_SCRIPT  = "/usr/bin/sudo -E ${SCRIPTS_DIR}/deploy-build.sh"
    ROLLBACK_SCRIPT = "/usr/bin/sudo -E ${SCRIPTS_DIR}/rollback.sh"

    //For rollback config
    env.DEPLOY_STATUS = "SUCCESS"
    echo "========================"
    sh 'printenv'
    echo "========================"
  }
  stage("1 of 3 Checkout") {
      try{
        echo "Start checkout on node: ${WORK_NODE}"
        checkout scm
        echo "Copy ${MYSQL_CONFIG} to ${SERVER_CONFIG_DIR}"
        sh "cp ${MYSQL_CONFIG} ${SERVER_CONFIG_DIR}"
      }catch(err) {
        println(err.getMessage());
        throw err
      }
    }

  stage("2 of 3 Build"){
      try{
         echo "Start build: '${VAPOR} build ${BUILD_PARAM}"
         sh "$VAPOR build $BUILD_PARAM"
      }catch(err) {
        println(err.getMessage());
        throw err
      }
  }


}
