#!groovy

    println "Hello world from di!"
    //def WORK_NODE = ''
    println "Branch ${env.BRANCH_NAME}"
sh "echo ${env.BRANCH_NAME} echo ${env.GIT_MESSAGE}"

    if (BRANCH_NAME == 'devops_develop') {
        println "ta da!!"
    }

 sh 'printenv'

    //println BRANCH_NAME //"Branch ${env.BRANCH_NAME}"

/*
    if (env.GIT_BRANCH.consits("develop")){  // 'origin/devops_develop'
        WORK_NODE = "chstage-node"
    } else {
        WORK_NODE = "chprod-node"
    }
*/
    //println "Work node is ${WORK_NODE}"
